version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: elasticsearch
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - elastic
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      xpack.security.enabled: false
      # ELASTIC_PASSWORD: Lkj#098#098
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    environment:
        ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        SERVER_HOST: 0.0.0.0
        SERVER_PORT: 5601
        CONFIG_RELOAD_AUTOMATIC: "true"
        CONFIG_RELOAD_INTERVAL: 3s
        # ELASTICSEARCH_USERNAME: kibana_system
        # KIBANA_PASSWORD: Lkj#098#098
    networks:
      - elastic
    depends_on:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:8.3.2
    volumes:
      - ./logstash_config/:/usr/share/logstash/config/
      - ./logstash_plugins/:/usr/share/logstash/pipeline/
    ports:
      - "5044:5044"
      - "8080:8080"
      - "9600:9600"
    environment:
        HTTP_HOST: 0.0.0.0
        CONFIG_RELOAD_AUTOMATIC: "true"
        CONFIG_RELOAD_INTERVAL: 3s
        MONITORING_ENABLED: false
        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elastic
    depends_on:
      - elasticsearch
      - kibana

networks:
  elastic:
    driver: bridge